---
- name: install riakcs
  apt: name={{ riakcs_package }} state=present
  when: riakcs_custom_package == False

- name: install riakcs custom
  command: dpkg --skip-same-version -i {{ riakcs_package }}
  register: dpkg_result
  changed_when: dpkg_result.stdout.startswith('Selecting')
  when: riakcs_custom_package != False

